# Create dataset

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
!pip install nltk
import nltk
from nltk.tokenize import word_tokenize
import string
from nltk.corpus import stopwords

Requirement already satisfied: nltk in /anaconda3/anaconda3/lib/python3.8/site-packages (3.5)
Requirement already satisfied: tqdm in /anaconda3/anaconda3/lib/python3.8/site-packages (from nltk) (4.47.0)
Requirement already satisfied: joblib in /anaconda3/anaconda3/lib/python3.8/site-packages (from nltk) (0.16.0)
Requirement already satisfied: click in /anaconda3/anaconda3/lib/python3.8/site-packages (from nltk) (7.1.2)
Requirement already satisfied: regex in /anaconda3/anaconda3/lib/python3.8/site-packages (from nltk) (2020.6.8)

In [3]:
import pandas as pd

#create movieid: cast list dictionary 
fc = pd.read_csv('FilmCast.csv', header = 0) #title 
fd = pd.read_csv('FilmDirector.csv', header = 0) #title 
person = pd.read_csv('Person.csv', header = 0) #title 
fc = pd.merge(person,fc,on='personID')
fd = pd.merge(person,fd,on='personID')
person = fc.append(fd)
movie_person = dict()
for i in range(len(person)):
    if person.iloc[i,2] in movie_person:
        movie_person[person.iloc[i,2]].append(person.iloc[i,1].replace(" ", ""))
    else:
        movie_person[person.iloc[i,2]] = [person.iloc[i,1].replace(" ", "")]

#create movieid: genre list dictionary 
genre = pd.read_csv('GenreOfFilm.csv', header = 0)
genlist = pd.read_csv('Genres.csv', header = 0)
gen = pd.merge(genlist,genre,on='genreID')
movie_genre = dict()
for i in range(len(gen)):
    if gen.iloc[i,2] in movie_genre:
        movie_genre[gen.iloc[i,2]].append(gen.iloc[i,0])
    else:
        movie_genre[gen.iloc[i,2]] = [gen.iloc[i,0]]
        
        
movies = pd.read_csv('Movie.csv', header = 0) #title 
for i in range(len(movies)):
    movies.iloc[i,4] = [' '.join(word for word in movie_genre[movies.iloc[i,0]])]       #genre list for that movieid
    movies.iloc[i,5] = [' '.join(word for word in movie_person[movies.iloc[i,0]])]      #cast list for that movieid
    
# movies = movies.rename(columns = {'total_ratings':'genre', 'rating_count':'cast'})

In [4]:
movies.head()

,movieID,title,year,description,total_ratings,rating_count
0,114709.0,Toy Story,1995,A cowboy doll is profoundly threatened and jea...,Animation,TomHanks TimAllen JimVarney DonRickles JohnLas...
1,113497.0,Jumanji,1995,When two kids find and play a magical board ga...,Adventure,RobinWilliams KirstenDunst BonnieHunt Jonathan...
2,113228.0,Grumpier Old Men,1995,John and Max resolve to save their beloved bai...,Comedy,SophiaLoren Ann-Margret JackLemmon WalterMatth...
3,114885.0,Waiting to Exhale,1995,"Based on Terry McMillan's novel, this film fol...",Comedy,AngelaBassett WhitneyHouston LelaRochon Lorett...
4,113041.0,Father of the Bride Part II,1995,George Banks must deal not only with the pregn...,Comedy,SteveMartin DianeKeaton MartinShort KimberlyWi...

# Clean up description

In [5]:
stop_words = set(stopwords.words('english'))
for i in range(len(movies)):
    try:
        desc = movies.iloc[i,3]
        tokens = word_tokenize(desc)
        words = [word for word in tokens if word.isalpha()]              #remove non letters
        words = [word for word in words if not word in stop_words]       #remove stopwords
        words = [word.lower() for word in words]                         #convert to lower case
        movies.iloc[i,3] = ' '.join(word for word in words)              #join as a single string
    except:
        movies.iloc[i,3] = ''                                            #if nan replace with empty string

In [6]:
movies.head()

,movieID,title,year,description,total_ratings,rating_count
0,114709.0,Toy Story,1995,a cowboy doll profoundly threatened jealous ne...,Animation,TomHanks TimAllen JimVarney DonRickles JohnLas...
1,113497.0,Jumanji,1995,when two kids find play magical board game rel...,Adventure,RobinWilliams KirstenDunst BonnieHunt Jonathan...
2,113228.0,Grumpier Old Men,1995,john max resolve save beloved bait shop turnin...,Comedy,SophiaLoren Ann-Margret JackLemmon WalterMatth...
3,114885.0,Waiting to Exhale,1995,based terry mcmillan novel film follows four d...,Comedy,AngelaBassett WhitneyHouston LelaRochon Lorett...
4,113041.0,Father of the Bride Part II,1995,george banks must deal pregnancy daughter also...,Comedy,SteveMartin DianeKeaton MartinShort KimberlyWi...

# Bag of words

In [7]:
for i in range(len(movies)):
    movies.iloc[i,1] = [str(movies.iloc[i,1]) + ' ' + str(movies.iloc[i,2]) + ' ' + str(movies.iloc[i,3]) + ' ' + str(movies.iloc[i,4])]
movies.drop(columns = ['year','description','total_ratings','rating_count'], inplace = True)
movies = movies.rename(columns = {'title':'bag_of_words'})
movies.head()

    movieID                                       bag_of_words
0  114709.0  Toy Story 1995 a cowboy doll profoundly threat...
1  113497.0  Jumanji 1995 when two kids find play magical b...
2  113228.0  Grumpier Old Men 1995 john max resolve save be...
3  114885.0  Waiting to Exhale 1995 based terry mcmillan no...
4  113041.0  Father of the Bride Part II 1995 george banks ...

# model

In [8]:
import time
start = time.time()

count = CountVectorizer()
matrix = count.fit_transform(movies['bag_of_words'])   #generating the count matrix

cosine_sim = cosine_similarity(matrix, matrix)         #cosine similarity matrix
print(time.time() - start)

2.0399422645568848

In [11]:
#save the data as a dataframe 
sim = pd.DataFrame(data=cosine_sim[0:,0:],index = movies.movieID, columns=movies.movieID) #values, index, columns
sim['movieID'] = sim.index                        #add a column for movieID
sim.to_csv('sim.csv',index=False)               #save to file

In [12]:
sim.head()

movieID,114709.0,113497.0,113228.0,114885.0,113041.0,113277.0,114319.0,112302.0,114576.0,113189.0,...,7374948.0,7131622.0,6751668.0,6105098.0,6806448.0,2935510.0,7349950.0,7286456.0,9243946.0,movieID
movieID,,,,,,,,,,,,,,,,,,,,,
114709.0,1.000000,0.048912,0.095673,0.055641,0.051299,0.054074,0.054074,0.051299,0.051299,0.042601,...,0.000000,0.000000,0.000000,0.051299,0.000000,0.000000,0.000000,0.0,0.000000,114709.0
113497.0,0.048912,1.000000,0.044455,0.051709,0.047673,0.050252,0.050252,0.190693,0.143019,0.039590,...,0.040291,0.000000,0.000000,0.000000,0.000000,0.044455,0.047673,0.0,0.000000,113497.0
113228.0,0.095673,0.044455,1.000000,0.101144,0.093250,0.049147,0.098295,0.046625,0.046625,0.038720,...,0.039406,0.041703,0.050572,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,113228.0
114885.0,0.055641,0.051709,0.101144,1.000000,0.108465,0.057166,0.114332,0.054233,0.054233,0.090075,...,0.045835,0.048507,0.058824,0.000000,0.000000,0.000000,0.000000,0.0,0.042875,114885.0
113041.0,0.051299,0.047673,0.093250,0.108465,1.000000,0.052705,0.105409,0.050000,0.050000,0.041523,...,0.042258,0.044721,0.054233,0.100000,0.040161,0.046625,0.000000,0.0,0.000000,113041.0

# Query dataframe (can be done on sql)

In [17]:
# sim = pd.read_csv('sim.csv', header = 0)   
inputid = 113041.0                                          #should be the value from the user's input
row_index = sim.index[sim['movieID'] == inputid][0]
arr = sim.iloc[row_index]
top_1000 = list((arr.sort_values(ascending = False)[2:1002]).index) #top 1000 similar movieids as a list

In [18]:
top_1000

['101862.0',
 '42451.0',
 '349205.0',
 '216787.0',
 '102465.0',
 '31885.0',
 '110216.0',
 '880502.0',
 '97390.0',
 '59821.0',
 '331933.0',
 '213790.0',
 '756729.0',
 '4270516.0',
 '361620.0',
 '111309.0',
 '95990.0',
 '95705.0',
 '191043.0',
 '85959.0',
 '292542.0',
 '50658.0',
 '118804.0',
 '107207.0',
 '112572.0',
 '112508.0',
 '300051.0',
 '120533.0',
 '189998.0',
 '1578275.0',
 '120686.0',
 '112579.0',
 '109045.0',
 '82517.0',
 '327162.0',
 '98503.0',
 '93857.0',
 '129280.0',
 '167260.0',
 '325980.0',
 '1058017.0',
 '365885.0',
 '98621.0',
 '1951261.0',
 '90985.0',
 '97108.0',
 '111752.0',
 '118836.0',
 '95497.0',
 '107225.0',
 '114887.0',
 '357110.0',
 '120737.0',
 '65466.0',
 '35211.0',
 '60522.0',
 '945356.0',
 '112499.0',
 '1756750.0',
 '107151.0',
 '91480.0',
 '4225622.0',
 '1450321.0',
 '65777.0',
 '97368.0',
 '97523.0',
 '139239.0',
 '70040.0',
 '458364.0',
 '413893.0',
 '365748.0',
 '4669788.0',
 '86425.0',
 '47898.0',
 '1219342.0',
 '114214.0',
 '100240.0',
 '96874.0',
 '93936.0',
 '304262.0',
 '151137.0',
 '414951.0',
 '2210479.0',
 '1659343.0',
 '437857.0',
 '105121.0',
 '1379177.0',
 '68361.0',
 '80948.0',
 '368709.0',
 '323298.0',
 '3792960.0',
 '250310.0',
 '70819.0',
 '109890.0',
 '92925.0',
 '112255.0',
 '1073498.0',
 '102510.0',
 '212380.0',
 '292644.0',
 '113321.0',
 '95488.0',
 '60438.0',
 '96969.0',
 '354899.0',
 '90848.0',
 '71487.0',
 '94678.0',
 '775529.0',
 '1545660.0',
 '61722.0',
 '68205.0',
 '82186.0',
 '2910274.0',
 '120773.0',
 '39808.0',
 '39853.0',
 '3464902.0',
 '113211.0',
 '186151.0',
 '110428.0',
 '2125435.0',
 '105197.0',
 '31580.0',
 '1318514.0',
 '107943.0',
 '2172985.0',
 '95736.0',
 '85794.0',
 '307109.0',
 '58886.0',
 '56552.0',
 '114057.0',
 '18037.0',
 '1740047.0',
 '165874.0',
 '77869.0',
 '120823.0',
 '1440345.0',
 '3896198.0',
 '1650043.0',
 '90886.0',
 '18773.0',
 '119304.0',
 '2452386.0',
 '492956.0',
 '467406.0',
 '419198.0',
 '110074.0',
 '59229.0',
 '79095.0',
 '1935896.0',
 '80539.0',
 '95327.0',
 '239986.0',
 '1033575.0',
 '98532.0',
 '314786.0',
 '3021360.0',
 '119905.0',
 '12349.0',
 '2576852.0',
 '256524.0',
 '92106.0',
 '93220.0',
 '117826.0',
 '120642.0',
 '80439.0',
 '87544.0',
 '478304.0',
 '45464.0',
 '1810683.0',
 '363771.0',
 '44876.0',
 '1018785.0',
 '113755.0',
 '72848.0',
 '112896.0',
 '81150.0',
 '114666.0',
 '71562.0',
 '91653.0',
 '53925.0',
 '56172.0',
 '980970.0',
 '103060.0',
 '180052.0',
 '120777.0',
 '313196.0',
 '117372.0',
 '73629.0',
 '86112.0',
 '419843.0',
 '70334.0',
 '114852.0',
 '92965.0',
 '111622.0',
 '107148.0',
 '48956.0',
 '3172532.0',
 '795421.0',
 '165929.0',
 '97276.0',
 '113613.0',
 '98308.0',
 '436689.0',
 '89853.0',
 '76095.0',
 '96734.0',
 '4622512.0',
 '330243.0',
 '5657846.0',
 '58947.0',
 '286499.0',
 '296572.0',
 '311648.0',
 '89907.0',
 '41094.0',
 '411477.0',
 '113756.0',
 '72081.0',
 '19254.0',
 '384642.0',
 '112966.0',
 '97443.0',
 '84726.0',
 '1657299.0',
 '102926.0',
 '2310332.0',
 '242252.0',
 '62873.0',
 '1135092.0',
 '2056771.0',
 '46534.0',
 '53219.0',
 '25878.0',
 '116985.0',
 '154421.0',
 '119190.0',
 '278500.0',
 '93091.0',
 '5619332.0',
 '76734.0',
 '52126.0',
 '54460.0',
 '102598.0',
 '73802.0',
 '88000.0',
 '362227.0',
 '158583.0',
 '34172.0',
 '113729.0',
 '115819.0',
 '54033.0',
 '367089.0',
 '83851.0',
 '160916.0',
 '172396.0',
 '65063.0',
 '66195.0',
 '87700.0',
 '113972.0',
 '120596.0',
 '265666.0',
 '385267.0',
 '113403.0',
 '5294550.0',
 '80402.0',
 '842926.0',
 '120646.0',
 '2103281.0',
 '76716.0',
 '2404461.0',
 '460780.0',
 '117628.0',
 '403508.0',
 '78790.0',
 '3750872.0',
 '348593.0',
 '236784.0',
 '64117.0',
 '1878870.0',
 '98193.0',
 '68935.0',
 '112435.0',
 '39169.0',
 '91605.0',
 '39566.0',
 '91778.0',
 '119746.0',
 '2015381.0',
 '77504.0',
 '1326972.0',
 '5536736.0',
 '113409.0',
 '109370.0',
 '117773.0',
 '102034.0',
 '113416.0',
 '4276820.0',
 '327247.0',
 '82100.0',
 '19777.0',
 '71994.0',
 '401383.0',
 '57413.0',
 '116752.0',
 '165982.0',
 '1568921.0',
 '98502.0',
 '109439.0',
 '87365.0',
 '42876.0',
 '115836.0',
 '111094.0',
 '141974.0',
 '371246.0',
 '335345.0',
 '63759.0',
 '50781.0',
 '40679.0',
 '1723121.0',
 '218967.0',
 '2177771.0',
 '116583.0',
 '70509.0',
 '388182.0',
 '104691.0',
 '1769363.0',
 '338188.0',
 '94332.0',
 '115744.0',
 '100258.0',
 '36506.0',
 '3742378.0',
 '2319580.0',
 '120125.0',
 '102729.0',
 '120483.0',
 '43461.0',
 '65446.0',
 '112642.0',
 '1343097.0',
 '47422.0',
 '1043726.0',
 '61847.0',
 '473075.0',
 '1411697.0',
 '115669.0',
 '901487.0',
 '68408.0',
 '67065.0',
 '47094.0',
 '112922.0',
 '108069.0',
 '362590.0',
 '103110.0',
 '86129.0',
 '167261.0',
 '93507.0',
 '422093.0',
 '106977.0',
 '483726.0',
 '54310.0',
 '91630.0',
 '97322.0',
 '4048272.0',
 '108525.0',
 '33836.0',
 '61811.0',
 '784972.0',
 '100740.0',
 '308878.0',
 '93148.0',
 '144201.0',
 '2388637.0',
 '2785032.0',
 '120861.0',
 '2473510.0',
 '36868.0',
 '48347.0',
 '29146.0',
 '95675.0',
 '1032825.0',
 '1441912.0',
 '98382.0',
 '314630.0',
 '101640.0',
 '112883.0',
 '38733.0',
 '1730768.0',
 '1976000.0',
 '84329.0',
 '274558.0',
 '2870756.0',
 '87425.0',
 '16220.0',
 '56241.0',
 '238546.0',
 '100828.0',
 '1504320.0',
 '1959563.0',
 '93756.0',
 '69768.0',
 '445922.0',
 '254099.0',
 '1300851.0',
 '1231580.0',
 '99088.0',
 '1307068.0',
 '176269.0',
 '122459.0',
 '57840.0',
 '1298650.0',
 '106308.0',
 '120747.0',
 '144120.0',
 '79826.0',
 '92546.0',
 '490579.0',
 '111512.0',
 '114272.0',
 '2083383.0',
 '5592248.0',
 '144214.0',
 '212338.0',
 '89385.0',
 '92608.0',
 '317676.0',
 '119324.0',
 '31060.0',
 '82351.0',
 '110322.0',
 '115986.0',
 '95989.0',
 '64381.0',
 '114131.0',
 '38969.0',
 '84649.0',
 '112346.0',
 '35019.0',
 '418689.0',
 '166252.0',
 '107985.0',
 '31022.0',
 '64840.0',
 '118826.0',
 '35169.0',
 '120746.0',
 '62952.0',
 '99165.0',
 '3722070.0',
 '1135525.0',
 '1727388.0',
 '1170358.0',
 '3416744.0',
 '4972.0',
 '91326.0',
 '224578.0',
 '87050.0',
 '98194.0',
 '25452.0',
 '69947.0',
 '185014.0',
 '1465487.0',
 '460745.0',
 '317198.0',
 '103030.0',
 '48750.0',
 '100134.0',
 '32701.0',
 '3312830.0',
 '421994.0',
 '4481514.0',
 '120728.0',
 '63227.0',
 '36112.0',
 '120831.0',
 '49474.0',
 '87799.0',
 '2980648.0',
 '39190.0',
 '55312.0',
 '114194.0',
 '8695030.0',
 '97050.0',
 '1645170.0',
 '1196141.0',
 '55913.0',
 '160509.0',
 '84814.0',
 '384819.0',
 '50738.0',
 '293508.0',
 '3289956.0',
 '61789.0',
 '98090.0',
 '99180.0',
 '52905.0',
 '102555.0',
 '384680.0',
 '26138.0',
 '377092.0',
 '120902.0',
 '65462.0',
 '902290.0',
 '993846.0',
 '404802.0',
 '119115.0',
 '227538.0',
 '110622.0',
 '95243.0',
 '70735.0',
 '2980516.0',
 '110169.0',
 '250202.0',
 '86856.0',
 '4154796.0',
 '449851.0',
 '462338.0',
 '360009.0',
 '1226271.0',
 '138097.0',
 '46889.0',
 '69946.0',
 '58404.0',
 '58756.0',
 '87032.0',
 '112483.0',
 '1195478.0',
 '280030.0',
 '1390411.0',
 '32762.0',
 '142201.0',
 '324197.0',
 '456149.0',
 '84633.0',
 '387575.0',
 '82183.0',
 '100419.0',
 '250809.0',
 '760329.0',
 '131857.0',
 '401244.0',
 '1179025.0',
 '101523.0',
 '100196.0',
 '377818.0',
 '97481.0',
 '114906.0',
 '93051.0',
 '144528.0',
 '17075.0',
 '1397280.0',
 '66740.0',
 '71772.0',
 '105159.0',
 '51337.0',
 '52655.0',
 '112571.0',
 '75232.0',
 '113490.0',
 '113028.0',
 '84917.0',
 '337579.0',
 '1694020.0',
 '112716.0',
 '202677.0',
 '240402.0',
 '1491044.0',
 '99700.0',
 '808510.0',
 '4116284.0',
 '120618.0',
 '74102.0',
 '302640.0',
 '256009.0',
 '380623.0',
 '418819.0',
 '48424.0',
 '1935902.0',
 '4630562.0',
 '43456.0',
 '87428.0',
 '1134854.0',
 '329767.0',
 '165798.0',
 '359950.0',
 '359423.0',
 '110442.0',
 '95088.0',
 '114388.0',
 '338094.0',
 '59183.0',
 '106393.0',
 '4154756.0',
 '118691.0',
 '149691.0',
 '97474.0',
 '59017.0',
 '171580.0',
 '120894.0',
 '114296.0',
 '60424.0',
 '108122.0',
 '114011.0',
 '91777.0',
 '113762.0',
 '15841.0',
 '125022.0',
 '63462.0',
 '1245492.0',
 '422861.0',
 '3097204.0',
 '116240.0',
 '37536.0',
 '1399103.0',
 '116754.0',
 '2203939.0',
 '374900.0',
 '111666.0',
 '112887.0',
 '120034.0',
 '1646987.0',
 '218378.0',
 '101902.0',
 '2234155.0',
 '469754.0',
 '67778.0',
 '117104.0',
 '82934.0',
 '494238.0',
 '118715.0',
 '389828.0',
 '191133.0',
 '70294.0',
 '75132.0',
 '104940.0',
 '99472.0',
 '33045.0',
 '110123.0',
 '5186714.0',
 '352520.0',
 '238924.0',
 '52738.0',
 '59825.0',
 '3120280.0',
 '2262227.0',
 '1104001.0',
 '116516.0',
 '71913.0',
 '112625.0',
 '2692250.0',
 '114241.0',
 '84597.0',
 '66565.0',
 '190138.0',
 '116442.0',
 '242653.0',
 '119910.0',
 '1270761.0',
 '1322312.0',
 '81470.0',
 '120770.0',
 '1314228.0',
 '990407.0',
 '4302938.0',
 '85980.0',
 '83530.0',
 '84234.0',
 '2084970.0',
 '111507.0',
 '114084.0',
 '110857.0',
 '100054.0',
 '109484.0',
 '1186370.0',
 '72653.0',
 '37674.0',
 '115438.0',
 '4827558.0',
 '240462.0',
 '74119.0',
 '114496.0',
 '191397.0',
 '48977.0',
 '202641.0',
 '455590.0',
 '109504.0',
 '107206.0',
 '77321.0',
 '1763303.0',
 '91541.0',
 '101761.0',
 '66206.0',
 '114345.0',
 '154443.0',
 '59221.0',
 '466342.0',
 '58450.0',
 '110366.0',
 '346336.0',
 '1130988.0',
 '81529.0',
 '1462769.0',
 '232500.0',
 '114113.0',
 '35567.0',
 '109593.0',
 '1287468.0',
 '114888.0',
 '58333.0',
 '110189.0',
 '3450958.0',
 '2006040.0',
 '1324999.0',
 '168501.0',
 '88414.0',
 '31448.0',
 '75718.0',
 '64030.0',
 '79833.0',
 '386140.0',
 '97223.0',
 '112462.0',
 '119164.0',
 '2709768.0',
 '453451.0',
 '40897.0',
 '80516.0',
 '77621.0',
 '38589.0',
 '87231.0',
 '1182350.0',
 '463985.0',
 '6412452.0',
 '89424.0',
 '97235.0',
 '463872.0',
 '2557490.0',
 '116705.0',
 '113303.0',
 '93624.0',
 '270846.0',
 '2118624.0',
 '168794.0',
 '424993.0',
 '120772.0',
 '90849.0',
 '2404311.0',
 '2279373.0',
 '116365.0',
 '52948.0',
 '78490.0',
 '119314.0',
 '172684.0',
 '92834.0',
 '319769.0',
 '473444.0',
 '6133130.0',
 '1645080.0',
 '101373.0',
 '9968.0',
 '115886.0',
 '362004.0',
 '107146.0',
 '117357.0',
 '4285496.0',
 '93744.0',
 '288330.0',
 '113188.0',
 '113870.0',
 '388419.0',
 '61749.0',
 '120878.0',
 '101605.0',
 '2235108.0',
 '160513.0',
 '14538.0',
 '46911.0',
 '206013.0',
 '166943.0',
 '100557.0',
 '1931435.0',
 '3860916.0',
 '61395.0',
 '68638.0',
 '113243.0',
 '4986098.0',
 '1308138.0',
 '113749.0',
 '114478.0',
 '1716772.0',
 '264150.0',
 '1687281.0',
 '2234003.0',
 '56732.0',
 '331952.0',
 '23563.0',
 '141098.0',
 '151738.0',
 '406650.0',
 '115988.0',
 '163187.0',
 '70791.0',
 '117057.0',
 '103184.0',
 '57449.0',
 '125664.0',
 '116823.0',
 '445946.0',
 '1024255.0',
 '98536.0',
 '76257.0',
 '64603.0',
 '401085.0',
 '465234.0',
 '41509.0',
 '832266.0',
 '93737.0',
 '42276.0',
 '116095.0',
 '901476.0',
 '32143.0',
 '481141.0',
 '61735.0',
 '79470.0',
 '255653.0',
 '116756.0',
 '95403.0',
 '164184.0',
 '424823.0',
 '51776.0',
 '2990140.0',
 '492619.0',
 '377107.0',
 '368667.0',
 '119062.0',
 '95593.0',
 '118789.0',
 '93894.0',
 '95179.0',
 '89370.0',
 '56095.0',
 '486576.0',
 '112427.0',
 '357413.0',
 '60196.0',
 '1078912.0',
 '119361.0',
 '1046173.0',
 '3741700.0',
 '93073.0',
 '108187.0',
 '106408.0',
 '311113.0',
 '119987.0',
 '63056.0',
 '68519.0',
 '1289403.0',
 '213203.0',
 '379889.0',
 '270980.0',
 '2179121.0',
 '114825.0',
 '1981677.0',
 '1174730.0',
 '411195.0',
 '113464.0',
 '111252.0',
 '3606756.0',
 '112606.0',
 '819714.0',
 '2756032.0',
 '62407.0',
 '95169.0',
 '112438.0',
 '58571.0',
 '258273.0',
 '119142.0',
 '60182.0',
 '80487.0',
 '1334553.0',
 '119887.0',
 '198021.0',
 '128445.0',
 '114571.0',
 '790623.0',
 '814130.0',
 '103786.0',
 '1502404.0',
 '790604.0',
 '93437.0',
 '1637706.0',
 '198386.0',
 '7668870.0',
 '825236.0',
 '79550.0',
 '243493.0',
 '92605.0',
 '55277.0',
 '1458175.0',
 '250274.0',
 '102411.0',
 '398883.0',
 '1054606.0',
 '242508.0',
 '1714206.0',
 '113448.0',
 '80339.0',
 '188453.0',
 '235060.0',
 '97457.0',
 '73766.0',
 '241223.0',
 '328589.0',
 '93389.0',
 '75200.0',
 '81269.0',
 '387514.0',
 '169547.0',
 '203019.0',
 '882977.0',
 '107507.0',
 '290332.0',
 '80492.0',
 '93412.0',
 '417001.0',
 '898367.0',
 '110955.0',
 '47437.0',
 '203166.0',
 '355702.0',
 '119670.0',
 '68687.0',
 '1134629.0',
 '2061702.0',
 '1817273.0',
 '73650.0',
 '119052.0',
 '431021.0',
 '480271.0',
 '97236.0',
 '76363.0',
 '3949660.0',
 '87298.0',
 '103207.0',
 '449088.0',
 '121765.0',
 '96913.0',
 '373051.0',
 '914798.0',
 '287717.0',
 '70291.0',
 '499448.0',
 '5666304.0',
 '292963.0',
 '74718.0',
 '112541.0',
 '44744.0',
 '112854.0',
 '1038043.0',
 '1000774.0',
 '4686844.0',
 '168449.0',
 '427954.0',
 '1509767.0',
 '1114677.0',
 '112342.0',
 '1542768.0',
 '426578.0',
 '811138.0',
 '109327.0',
 '1540133.0',
 '146984.0',
 '124298.0',
 '318283.0',
 '87932.0',
 '45152.0',
 '113161.0',
 '120142.0',
 '32904.0',
 '113851.0',
 '120645.0',
 '91877.0',
 '105151.0',
 '113957.0',
 '78504.0',
 '119109.0',
 '251031.0',
 '75040.0',
 '5610554.0',
 '98354.0',
 '306685.0',
 '93886.0',
 '71464.0',
 '1860242.0',
 '88461.0',
 '889573.0']